server_addr = "127.0.0.1"
server_port = 17000
log_level = "info"

[auth]
method = "token"
token = "replace_with_token"

[transport]
protocol = "kcp"
pool_count = 1

[[proxies]]
name = "kcp_ssh"
type = "tcp"
local_ip = "127.0.0.1"
local_port = 22
remote_port = 6001
