server_addr = "your.server.name"
server_port = 17000
client_id = "http-subdomain-node-1"

log_level = "info"

[auth]
method = "token"
token = "replace_with_token"

[transport]
protocol = "websocket"
tcp_mux = true
pool_count = 1

[[proxies]]
name = "app_http_subdomain"
type = "http"
local_ip = "127.0.0.1"
local_port = 8080
subdomain = "app"
