server_addr = "your.server.name"
server_port = 443

log_level = "info"

[auth]
method = "token"
token = "replace_with_token"

[transport]
protocol = "websocket"
tcp_mux = true
pool_count = 1

[transport.tls]
enable = true
trusted_ca_file = "/etc/arp/server.crt"
server_name = "your.server.name"

[[proxies]]
name = "ssh"
type = "tcp"
local_ip = "127.0.0.1"
local_port = 22
remote_port = 6001
